n = input('Digite algo: ')
print('O tipo primitivo desse valor e de: ',type(n))
print('só tem espaços? ', n.isspace())
print('é um numero? ', n.isnumeric())
print('é alfabetico? ', n.isalpha())
print('é alfanumerico? ', n.isalnum())
print('esta em minusculas? ', n.islower())
print('esta em maiusculas? ', n.isupper())
print('esta captalizada? ', n.istitle())
